version: '3.8'
services:
    red-bot:
        build: .
        container_name: RedBot
        restart: unless-stopped
        environment:
            INSTANCE_NAME: "BenAnnaBot"
            PREFIX: "!"
        volumes:
            - ${DATA_PATH}:/redbot/data
