services:
  db:
    restart: always
    image: mariadb:10.11
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_LOG_CONSOLE=true
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - ${DATA_PATH}/mysql/db:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
    networks:
      - seafile-net

  memcached:
    restart: always
    image: memcached:1.6.18
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - seafile-net

  elasticsearch:
    restart: always
    image: elasticsearch:8.6.2
    container_name: seafile-elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    volumes:
      - ${DATA_PATH}/elasticsearch/data:/usr/share/elasticsearch/data  # Requested, specifies the path to Elasticsearch data persistent store.
    networks:
      - seafile-net
          
  seafile:
    restart: always
    image: docker.seadrive.org/seafileltd/seafile-pro-mc:latest
    container_name: seafile
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ${DATA_PATH}/data:/shared   # Requested, specifies the path to Seafile data persistent store.
      - type: bind
        source: ${FUSE_PATH}
        target: /seafile-fuse
        bind:
          propagation: rshared
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=${DB_PASSWORD}
      - TIME_ZONE=America/New_York 
      - SEAFILE_ADMIN_EMAIL=${ADMIN_EMAIL} 
      - SEAFILE_ADMIN_PASSWORD=${ADMIN_PASSWORD}   
      - SEAFILE_SERVER_LETSENCRYPT=false  
      - SEAFILE_SERVER_HOSTNAME=${HOSTNAME}:${EXTERNAL_HTTPS_PORT}
    depends_on:
      - db
      - memcached
      - elasticsearch
    networks:
      - seafile-net
    privileged: true # for fuse
    cap_add:
        - SYS_ADMIN

networks:
  seafile-net:
