all:
  vars:
    timezone: EST
    ansible_connection: local
    root_domain: benanna.club
    docker_network_subnet: 172.20.0.0/16
    service_user: homelab
    service_group: homelab

    services_config_path: /opt/homelab/service-configs
    services_data_path: /opt/homelab/data/service-data
    enabled_services:
      - Redbot
      - Seafile
      - Immich
      - Nginx
      - ddns
      - HomeAssistant
      - Omada

    seafile:
      fuse_path: /opt/homelab/data/seafile-fuse
      # from https://customer.seafile.com/downloads
      docker_username: seafile

    immich:
      immich_version: release
      db_hostname: immich_postgres
      db_username: postgres
      db_database_name: immich
      redis_hostname: immich_redis

    nginx:
      conf_path: "{{ services_config_path }}/Nginx/config"
      certs_path: "{{ services_data_path }}/Nginx/certs"
      static_path: "{{ services_config_path }}/Nginx/static"
      letsencrypt_lib_path: "{{ services_data_path }}/Nginx/letsencrypt"
      cloudflare_credentials_path: "{{ services_config_path }}/Nginx/cloudflare.ini"

    homeassistant:
      conf_path: "{{ services_data_path }}/HomeAssistant/config"

  hosts:
    localhost:
      external_hostname: "{{ root_domain }}"
      certbot_env: prod
    vagrant:
      external_hostname: "localdev.{{ root_domain }}"
      certbot_env: staging
