all:
  vars:
    timezone: EST
    ansible_connection: local
    root_domain: benanna.club
    docker_network_subnet: 172.20.0.0/16
    service_user: homelab
    service_group: homelab

    services_config_path: /opt/homelab/service-configs
    services_data_path: /opt/homelab/data/service-data
    enabled_services:
      - Redbot
      - Seafile
      - Immich
      - Nginx
      - ddns
      - HomeAssistant
      - Omada
      - AdGuard
      - Code
      - Kuma

    crons_config_path: /opt/homelab/cron-configs
    crons_data_path: /opt/homelab/data/cron-data
    enabled_crons:
      - Certbot
      - GithubMirror

    seafile:
      fuse_path: /opt/homelab/data/seafile-fuse
      # from https://customer.seafile.com/downloads
      docker_username: seafile

    immich:
      immich_version: release
      db_hostname: immich_postgres
      db_username: postgres
      db_database_name: immich
      redis_hostname: immich_redis

    nginx:
      conf_path: "{{ services_config_path }}/Nginx/config"
      certs_path: "{{ services_data_path }}/Nginx/certs"
      static_path: "{{ services_config_path }}/Nginx/static"
      letsencrypt_lib_path: "{{ services_data_path }}/Nginx/letsencrypt"
      cloudflare_credentials_path: "{{ services_config_path }}/Nginx/cloudflare.ini"

    homeassistant:
      conf_path: "{{ services_data_path }}/HomeAssistant/config"

    github_mirror:
      repo_path: "{{ crons_data_path }}/GithubMirror"
      repo_list:
        - name: Homelab
          repo_url: "https://github.com/benreid24/Homelab.git"
        - name: BLIB
          repo_url: "https://github.com/benreid24/BLIB.git"
        - name: RPS-Godot
          repo_url: "https://github.com/benreid24/RPS-Godot.git"
        - name: FriendCal
          repo_url: "https://github.com/benreid24/FriendCal.git"
        - name: Outpost-Engine
          repo_url: "https://github.com/benreid24/Outpost-Engine.git"
        - name: Stellaru
          repo_url: "https://github.com/benreid24/Stellaru.git"
        - name: BLIB-Template
          repo_url: "https://github.com/benreid24/BLIB-Template.git"
        - name: Peoplemon-3
          repo_url: "https://github.com/benreid24/Peoplemon-3.git"
        - name: FastCopy
          repo_url: "https://github.com/benreid24/FastCopy.git"
        - name: Minecraft-Runner
          repo_url: "https://github.com/benreid24/Minecraft-Runner.git"
        - name: Animation-Editor-2
          repo_url: "https://github.com/benreid24/Animation-Editor-2.git"
        - name: Oatmeal
          repo_url: "https://github.com/benreid24/Oatmeal.git"
        - name: Wedding-Website
          repo_url: "https://github.com/benreid24/wedding-site.git"
        - name: Space-Race
          repo_url: "https://github.com/benreid24/Space-Race.git"
        - name: Ignis-Cor
          repo_url: "https://github.com/benreid24/Ignus-Cor.git"
        - name: Rover
          repo_url: "https://github.com/benreid24/Rover.git"
        - name: Peoplemon
          repo_url: "https://github.com/benreid24/Peoplemon.git"
        - name: Animation-Editor
          repo_url: "https://github.com/benreid24/Animation-Editor.git"
        - name: 22ndCG-Website
          repo_url: "https://github.com/benreid24/22ndCG-Website.git"
        - name: Personal-Website
          repo_url: "https://github.com/benreid24/Personal-Website.git"
        - name: QuadPilot
          repo_url: "https://github.com/benreid24/QuadPilot.git"

    satisfactory_saves_path: /opt/homelab/data/satisfactory-saves

  hosts:
    localhost:
      external_hostname: "{{ root_domain }}"
      certbot_env: prod
    vagrant:
      external_hostname: "localdev.{{ root_domain }}"
      certbot_env: staging
