all:
  hosts:
    localhost:
      external_hostname: sirgeorgelordofthevoid.com
    vagrant:
      external_hostname: 192.168.56.10

  vars:
      timezone: EST
      ansible_connection: local
      services_config_path: /opt/homelab/services
      services_data_path: /opt/homelab/data
      enabled_services:
        - Redbot
        - Seafile
        - Immich
        - Nginx

      seafile:
        http_port: 12080
        https_port: 13443
        fuse_path: /data/seafile-fuse
        # from https://customer.seafile.com/downloads
        docker_username: seafile

      immich:
        immich_version: release
        db_hostname: immich_postgres
        db_username: postgres
        db_database_name: immich
        redis_hostname: immich_redis
      
