all:
  hosts:
    localhost:
      external_hostname: sirgeorgelordofthevoid.com
    vagrant:
      external_hostname: homelab.lan

  vars:
      timezone: EST
      ansible_connection: local
      services_config_path: /opt/homelab/service-configs
      services_data_path: /opt/homelab/data/service-data
      enabled_services:
        - Redbot
        - Seafile
        - Immich
        - Nginx

      seafile:
        fuse_path: /opt/homelab/data/seafile-fuse
        # from https://customer.seafile.com/downloads
        docker_username: seafile

      immich:
        immich_version: release
        db_hostname: immich_postgres
        db_username: postgres
        db_database_name: immich
        redis_hostname: immich_redis

      nginx:
        conf_path: "{{ services_config_path }}/Nginx/config"
        certs_path: "{{ services_config_path }}/Nginx/dev-certs"
        static_path: "{{ services_config_path }}/Nginx/static"
      
