name: nginx
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "${CONF_PATH}:/etc/nginx"
      - "${STATIC_PATH}:/var/www/html"
      - ${CERTS_PATH}:/etc/letsencrypt:ro
    restart: unless-stopped
    networks:
      - homelab

  certbot:
    image: certbot/dns-cloudflare
    container_name: certbot
    volumes:
      - ${CERTS_PATH}:/etc/letsencrypt
      - ${LETSENCRYPT_LIB_PATH}:/var/lib/letsencrypt
      - ${CLOUDFLARE_CREDENTIALS_PATH}:/etc/cloudflare.ini:ro
    # Don't auto-start, run manually
    entrypoint: /bin/sh
    command: -c "trap exit TERM; while :; do sleep 1; done"
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    external: true
