name: omada

services:
  omada-controller:
    image: mbentley/omada-controller:latest
    container_name: omada-controller
    volumes:
      - ${DATA_PATH}/data:/opt/tplink/EAPController/data
      - ${DATA_PATH}/work:/opt/tplink/EAPController/work
      - ${DATA_PATH}/logs:/opt/tplink/EAPController/logs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT=8088
      - PORTAL_HTTPS_PORT=8043
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    external: true
