$ANSIBLE_VAULT;1.1;AES256
38393230656364626362373563366532363236386539323865663637373733393838653761303761
6430303930323264323730323465343961363563313038640a336137393631303730313530396236
66306635313435633665633132333861656631313063363163613937643765663039623061366639
3832613732623366330a363634623938633830383438303362303432356336613864613862313237
36656434366336343236666561666634333638336636383737366636663932333761343538613332
63316434353336636563333635313438623361333664366238393264313636373939646637643166
37376431346437356431663530393361356231323665373266376366376636653131343633376566
38393965626238323463356665393861393431313336656135646537333366663636343131326532
38636236323663303264663933653231653836343763623435376531333430353564376663646466
63643161366530636336653434316461363137303735333563376436333563656563626636306332
34336437386561643462643430396439643562383562646137346331336362343238643464323930
66666562333430393362323832643564656332303432643131343061393461653331613330383031
37393964343936383535623061613163316133656539303564613338643163613433656165656431
37326535376566616635323033666131353638363562346239373733613461363739323639363639
31646566666238323463626465366331623262313365636431386538663164353661373031663735
31626236366535323564366138343539663937356262636265663463363430323763656336383032
64323932616662646537316233653266653263633334346535656131633231323839666137303639
65393237323139643839393661363562346265643233653136643530356634396632383464633934
35326666383731623565666362393934653730633165303135613565326634646136636632363363
31646433316530363837643461343736373634653466626338326335653137653033326538656363
65353062633261663633353239626338316264396135646536613964326433383032313064343637
30363439656563333135383936383236393966336138373531336531646261356162633239313366
39636239383266393830663730613164646662623132656339646362316132636332353863656132
37623731313166336332633430356132303461613937383638353739656162353565613437643535
32643063333236383839346561383037646238363638386261343733343334623539326335393531
32656665346132646565663466353030666434393466626332316130623632363936623031306665
64343831333363646235343465303466626565366165626365393231323030383963313138663165
65323162623438336636336136633164333063663332613137366135613833633763396235653563
65366266333036656565383234346139333633316131346364626130636165313536616563343434
33343763383366386430346434663331343039363133616465613431653664373232386431353764
33396539613133623639653339663862323634333830656138333836393062393330353666656461
66356666666536316433356431623835656564353333393533643235633266373436373932616363
65393835333437613263613731313662326438316237616566306339633863663333353431343937
32393565323761363736356462663665303734336364386239643561626366313635303366393938
373130393434626237646138333133393539
