- name: Write Home Assistant .env file
  copy:
    dest: "{{ services_config_path }}/HomeAssistant/.env"
    mode: '0600'
    content: |
      CONFIG_PATH={{ homeassistant.conf_path }}
      TIMEZONE={{ timezone }}
  register: homeassistant_config

- name: Mark HomeAssistant for restart
  set_fact:
    services_to_restart: "{{ services_to_restart | default([]) + ['HomeAssistant'] }}"
  when: homeassistant_config.changed
