- name: Create homelab group
  ansible.builtin.group:
    name: homelab

- name: Create service user
  ansible.builtin.user:
    name: homelab
    group: "{{ service_group }}"
    shell: /bin/bash
    create_home: yes

- name: Ensure homelab directory exists
  ansible.builtin.file:
    path: /opt/homelab
    state: directory
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    mode: '0755'
